### ISSUE TITLE
Can't run on linux

### ISSUE THREAD

**Issue by kartun83** [protyposis/yi-mirrorless-firmware-tools#1]
I'm new to JS, so may be you would be able to help with this issue.
`npm run unpack ./firmware.bin`
fails with this message : "const [key, value] = part.split('=');"

debug log from npm if it would help
[npm-debug.log](https://github.com/protyposis/yi-mirrorless-firmware-tools/files/1449427/npm-debug.log)

**Comment by protyposis** [comment]
You are running extremely old Node and NPM versions. Please update them and try again.

**Comment by protyposis** [comment]
Btw., the decompression step currently only works for FW 3.0-int because of a few hardcoded values (the logs say you're in a FW 2.0 folder).

**Comment by kartun83** [comment]
Ok. That node and npm are default in my repo, so. I'll recheck with most recent versions.
It's just a folder, I tried both 2.0 and 3.0, but since it's a syntax incompatibility with old version of node, I'll check again.

**Comment by protyposis** [comment]
Which distro are you using? Maybe [this](https://nodejs.org/en/download/package-manager/) helps? I'm currently on Node 6.11 so it does not have to be the most recent version.

**Comment by kartun83** [comment]
Linux mint 18.2
I've added their repo, updated node to 
npm@5.5.1
node@v8.9.0
```
0096818: ' ca', // SD card
        ^^^^^^^

SyntaxError: Decimals with leading zeros are not allowed in strict mode.
```
[2017-11-07T18_41_49_657Z-debug.log](https://github.com/protyposis/yi-mirrorless-firmware-tools/files/1451210/2017-11-07T18_41_49_657Z-debug.log)
Still no luck :(

**Comment by protyposis** [comment]
A small adjustment for the latest Node version was necessary. It's working now. Btw., thanks for being the first tester (or reporter)!

**Comment by jgquebec** [comment]
protyposis, i would like to know how i can use the file you create to unpack and hack yi m1 firmware. I can only open with textblock on windows. i would like to try to make bitrate 120mbs or more if possible and getting a flat image profil for the camera. Or if you can had that to a firmware update..,. thanks

**Comment by bmx22c** [comment]
Hello,
I'm writing on this closed issue because it has resolved my issue regarding the Node.js version you are using (you should write that in the README ;))
BUT (because there is a but) you seem to use the 3.0 firmware.
The problem is that yitechnology website only give the 3.1 FW.
Can you give us a link where we can download the same file please ?
Oh and, is that the INT or CN version ?
Thanks in advance, this is my first time commenting an issue on GitHub hahaha

**Comment by protyposis** [comment]
Hi @bmx22c, the unpacker is now working with every firmware version, so you can use 3.1 INT or CN. What exactly was your issue with Node.js, what should I add to the readme?

**Comment by bmx22c** [comment]
Hi,
Thank you for the update, I'll try that later ;)
The issue was that I tried on _3.0 INT_, _3.0 CN_ and _3.1 INT_, and it showed

> unknown version

type of error everytime I tried to unpack one of these.
And on top of that, I had some square bracket errors but it seems that it was because I used the latest _Node.js_ version, not the _6.X_.
So I think that you should write something about which version of _NPM_ and _Node.js_ we are suppose to work with, or at least, the version you are working with :)
Thanks in advance.

**Comment by protyposis** [comment]
Thanks, I added the recommended Node.js version `v8.10.0 LTS` to the readme. 

You should get `Cannot identify firmware` for CN firmware files because I have not added them to the table of known firmware versions in `versions.js`, but it's just a warning, not an error.

**Comment by bmx22c** [comment]
Thanks !
I'll look into that later on.
